### ISSUE TITLE
站点地址

### ISSUE THREAD

**Issue by lanhuaguizha** [halo-dev/halo-app#2]
App进入的时候首页需要填写“站点地址”“用户名”“密码”。能帮助我么[
![p](https://user-images.githubusercontent.com/9106780/58782146-52e74e00-8610-11e9-9151-de9e60ea97dc.png)
](url)

**Comment by ruibaby** [comment]
站点地址填入你的博客地址，用户名和密码填入你的博客的用户名密码即可。

**Comment by appdev** [comment]
这个是halo博客的后台管理APP，你需要先运行halo blog https://github.com/halo-dev/halo
