### ISSUE TITLE
依赖问题

### ISSUE THREAD

**Issue by MrHuangJser** [halo-dev/halo-app#5]
master分支clone到本地后pull_to_refresh的配置报错（可能是依赖版本的问题）

**Comment by MrHuangJser** [comment]
![image](https://user-images.githubusercontent.com/20551693/63644918-37c73e80-c726-11e9-8ab2-fc8cb7ecf43d.png)

插件文档的配置和你的配置对不上

**Comment by ruibaby** [comment]
似乎确实存在这个问题，你可以提交个 PR 哦。

**Comment by MrHuangJser** [comment]
> 似乎确实存在这个问题，你可以提交个 PR 哦。

已经提了pr

**Comment by ruibaby** [comment]
已合并。
